### PR TITLE
[Fix #1794] Check if there are tokens before accessing them

### LINKED ISSUE #1794: Cannot Read Files with only Newlines
A file containing only newlines makes rubocop fail with the following message.

```
An error occurred while Style/TrailingBlankLines cop was inspecting /Users/josua/projects/rubocop_sample/sample.rb.
undefined method `pos' for nil:NilClass
/Users/josua/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rubocop-0.30.0/lib/rubocop/cop/style/trailing_blank_lines.rb:19:in `investigate'
```

### PR DESCRIPTION
**Pull request by schmijos**
This PR fixes a problem occurring if rubocop scans empty files containing only new lines (#1794). I extracted the function determining the `__END__` token into an own method which respects empty token lists.

I'm not sure what to expect from autocorrection though.

### CODE REVIEW

**Comment by jonas054** [comment]
You should expect `autocorrect` to give `['', ''].join("\n")` for `EnforcedStyle: final_newline` and `['', '', ''].join("\n")` for `EnforcedStyle: final_blank_line`, so please add those examples.

Could you also add an example for a file containing only newlines and `__END__`? I know it's a weird case, but it's possible so we should support it.

**Comment by bbatsov** [comment]
Squash the commits into one and mention the bugfix in the changelog.

**Comment by schmijos** [comment]
Do you know what's wrong with the build? Running `bundle exec rspec && bundle exec rubocop` on my local machine results in all green.

**Comment by jonas054** [comment]
The same error exists on `master`. It seems that the `Documentation` cop doesn't work with parser 2.2.2.0. You can reproduce the error locally if you run `bundle update` first.

**Comment by bbatsov** [comment]
Rebase this on top of the current master.

**Comment by bbatsov** [comment]
Ah, you'll need to rebase again unfortunately.

**Comment by schmijos** [comment]
Ok, did it.

**Comment by bbatsov** [comment]
:+1: Thanks!
