### PR TITLE
[Fix #4006] Prevent `Style/WhileUntilModifier` from breaking on multiline modifier

### LINKED ISSUE #4006: Exception encountered while running the Style/WhileUntilModifier cop
Feel free to close this issue, I'm reporting since the message seemed to indicate you wanted to know about these errors. Example code to reproduce is included.

I received the following message after upgrading from 0.44.1 to 0.47.1:

```
An error occurred while Style/WhileUntilModifier cop was inspecting [redacted]
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.47.1 (using Parser 2.3.3.1, running on ruby 2.3.3 x86_64-darwin16)
```

Here's the complete backtrace (with unnecessary details redacted):

```
An error occurred while Style/WhileUntilModifier cop was inspecting [redacted].
undefined method `line' for nil:NilClass
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/mixin/statement_modifier.rb:60:in `commented?'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/mixin/statement_modifier.rb:16:in `non_eligible_node?'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/mixin/statement_modifier.rb:8:in `single_line_as_modifier?'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/style/while_until_modifier.rb:34:in `check'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/style/while_until_modifier.rb:15:in `on_while'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:43:in `block (2 levels) in on_while'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:102:in `with_cop_error_handling'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:42:in `block in on_while'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:41:in `each'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:41:in `on_while'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/ast/traversal.rb:154:in `on_block'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:47:in `on_block'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/ast/traversal.rb:95:in `on_def'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:47:in `on_def'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:47:in `on_begin'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/ast/traversal.rb:88:in `on_class'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:47:in `on_class'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/ast/traversal.rb:141:in `on_while'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:47:in `on_module'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/ast/traversal.rb:141:in `on_while'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:47:in `on_module'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:47:in `on_begin'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/ast/traversal.rb:12:in `walk'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:60:in `investigate'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/team.rb:121:in `investigate'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/team.rb:109:in `offenses'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/team.rb:51:in `inspect_file'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:248:in `inspect_file'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:195:in `block in do_inspection_loop'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:227:in `block in iterate_until_no_changes'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:220:in `loop'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:220:in `iterate_until_no_changes'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:191:in `do_inspection_loop'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:101:in `block in file_offenses'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:111:in `file_offense_cache'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:99:in `file_offenses'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:90:in `process_file'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:68:in `block in each_inspected_file'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:65:in `each'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:65:in `reduce'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:65:in `each_inspected_file'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:57:in `inspect_files'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:36:in `run'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cli.rb:72:in `execute_runner'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cli.rb:27:in `run'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/bin/rubocop:13:in `block in <top (required)>'
.rbenv/versions/2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/bin/rubocop:12:in `<top (required)>'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bin/rubocop:22:in `load'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bin/rubocop:22:in `<top (required)>'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
.rbenv/versions/2.3.3/bin/bundle:22:in `load'
.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
```

## Expected behavior

The source should be parsable.

## Actual behavior

The source is not parsable.

## Steps to reproduce the problem

Here's a cleaned-up version of the (regrettable) source that Rubocop is unable to parse:

```ruby
"00001".tap { |prefix|
  prefix.succ! while some_variable ||
    some_other_variable
}
```

And is successfully parsed when written this way:

```ruby
"00001".tap { |prefix|
  prefix.succ! while some_variable || some_other_variable
}
```

## RuboCop version

0.47.1 (using Parser 2.3.3.1, running on ruby 2.3.3 x86_64-darwin16)

### PR DESCRIPTION
**Pull request by Drenmi**
This cop would break when encountering a multiline, unparenthesized `while` or `until` modifier. This change fixes that.

-----------------

Before submitting the PR make sure the following are checked:

* [X] Wrote [good commit messages][1].
* [X] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [X] Used the same coding conventions as the rest of the project.
* [X] Feature branch is up-to-date with `master` (if not - rebase it).
* [X] Squashed related commits together.
* [X] Added tests.
* [X] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [X] All tests are passing.
* [X] The new code doesn't generate RuboCop offenses.
* [X] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

**Comment by bbatsov** [comment]
👍

**Comment by marcandre** [comment]
For the record: this did prevent code breaking, but I believe this was the wrong fix and the spec is reversed by #8273: something in "modifier" form should never trigger an offense saying that the modifier form should be favored...
